#!/bin/sh

# Env variables required for programs started with `exec` from i3wm
export CM_HISTLENGTH=20 # For clipmenu: set length of output
export CM_OUTPUT_CLIP=1 # Clipmenu Default output to stdout

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -option caps:escape -layout us,ru -option grp:toggle

xmodmap ~/.Xmodmap

unclutter --jitter 5 --ignore-scrolling &
flameshot &
redshift &

clipmenud &

exec i3 
